### PR TITLE
Merge flip_ohc into dev

### PR DESCRIPTION
**Pull request by marosteg**
@camrinbraun...marked as "Can't automatically merge". Important one to incorporate for proper ohc likelihood orientation.

### CODE REVIEW

**Comment by camrinbraun** [comment]
maybe I fixed it but maybe not. everything is now wrapped in `if` statements which refer to the associated `flip` input var. probably worth testing.

**Comment by camrinbraun** [comment]
or do we just eliminate the `flip` portion of the `calc.xxx` functions because we now handle all that with `irregular_ncToRaster.r`?

**Comment by marosteg** [comment]
I just ran '''calc.ohc.par''' with '''flip_y = FALSE''' and it was oriented correctly. Re-running with '''flip_y = TRUE''' was incorrectly oriented. The '''flip_y''' portion can be eliminated now.

**Comment by camrinbraun** [comment]
this is awaiting further testing as `dev` currently functions as expected. leaving it for now in case we discover `dev` indeed fails and we need these changes, esp for `irregular_ncToRaster`

**Pull request closed without merging**
