### PR TITLE
start to handle 0 to 360

### PR DESCRIPTION
**Pull request by camrinbraun**
To my knowledge, we've never used `HMMoce` to build tracks on a 0 to 360 coord system before. This PR will (eventually) add that functionality.

@galuardi this is the beginning of what i expect will be several necessary changes to add this functionality

### CODE REVIEW

**Comment by camrinbraun** [comment]
Need to check the funs behave as expected with the different coord system.

- [ ] `get.env()`
  - [ ] OI sst
  - [ ] GHR
  - [ ] MUR
  - [ ] HYCOM
  - [ ] bathy
- [ ] likelihoods
  - [ ] calc.sst & par
  - [x] calc.lightloc (as expected)
  - [ ] calc.locs
  - [ ] calc.srss
  - [ ] calc.hycom & par
  - [ ] calc.ohc & par
  - [ ] calc.bottomTemp & par
  - [ ] calc.bathy & par
  - [ ] calc.errEll
- [ ] resample.grid
- [ ] make.L
  - [ ] coarse.L
- [ ] opt.params & nested `optim` and related funs
- [ ] HMM
  - [ ] filter
  - [ ] smoother
  - [ ] calc.track
- [ ] plotting

**Comment by camrinbraun** [comment]
Screen Shot 2020-11-04 at 1 00 06 PM

As ref'd above on `calc.track`, resulting track from an example albacore run suggested some jumping between E/W side of the basin. While this initially looked like a 180 to 360 issue, it appears the combined likelihoods effectively "pin" the filter/smoother outputs to one side of the basin or the other for extended periods of time, potentially due to similar oceanographic conditions. The only opportunity to switch sides of the basin is when the overall likelihood "allows" the north central Pacific as possible at which point the filter/smoother output is potentially allowed to cross. Thus, I suspect this is an issue with the observation likelihoods rather than with the package itself. Adding useful/reliable light-based longitude estimates **may** solve this as initial runs were not performed with any input from the light data which typically anchors longitude estimates effectively.

**Comment by camrinbraun** [comment]
@galuardi can you take a quick peek to make sure no major errors jump out at you? this will be merged with `dev` so i plan to continue testing it in the broader context of the trials with that branch

**Comment by galuardi** [comment]
am I looking at the calc.srss.r ? I went through the commits and they seem
straightforward. some date munging, a >180 warning, etc.

I agree on the albacore example. Without longitude, and in the case of
homogenous water masses along constant latitude, the fish probably won't
ever move.. Depth and temp alone can't do it in that case.

**Comment by camrinbraun** [comment]
> am I looking at the calc.srss.r ? I went through the commits and they seem straightforward. some date munging, a >180 warning, etc. I agree on the albacore example. Without longitude, and in the case of homogenous water masses along constant latitude, the fish probably won't ever move.. Depth and temp alone can't do it in that case.

No need to play with `calc.srss` unless you want to. Given how not useful that function typically is, I'm not worried about spending a bunch of time to make it play nice in 0 to 360 space. Sounds like you generally approve so I'll go ahead and merge.

**Pull request merged**
